<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" Version="6.6.184" />
    <PackageReference Include="Uno.WinUI.Skia.Gtk" Version="5.6.99" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="4.151.1" />
  </ItemGroup>
</Project>
